### PR TITLE
Feat: storage endpoint config

### LINKED ISSUE #42: Make object storage and region configurable
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

It possible to configure Yandex API endpoint, but storage endpoint bind to the constant in the source code, is it possible to allow customization of storage and region via configuration or, if supported by Yandex API, make it configurable via API calls? For first case I've modest patch, so would gladly post it as PR, if acceptable by code maintainers.

#### Use Case(s)

Use of Yandex packer plugin in custom/nonstandard environments with different storage endpoint and region settings.

#### Potential configuration

```
storage_endpoint: "storage.north-3.yandex-cloud.net"
storage_region: "ru-north-3"
```

### PR DESCRIPTION
**Pull request by karitra**
Enables additional options to make it possible to specify custom post-processing storage endpoint and region or allow storage endpoint to be discovered via YC API.   

Closes #42

### CODE REVIEW

**Review by Direnol — APPROVED** [review]
LGTM

**Comment by Direnol** [comment]
Hi @azr @nywilken !
Please review this PR.

**Comment by nywilken** [comment]
Hi there, I need to look into why the checks did not run. But this change requires that you run `make generate` to update the documentation and hclspec files for the newly added fields. Can you please run `make generate` or `go generate ./...`  and commit the generated files.

**Comment by nywilken** [comment]
@GennadySpb these changes look good to me. Could I get your eyes on it as well. @Direnol thanks for the review. I've ping the codeowner for review as well.

**Comment by karitra** [comment]
@nywilken, `make generate` done, PTAL.
https://github.com/hashicorp/packer-plugin-yandex/pull/43#issuecomment-1172591484

**Comment by GennadySpb** [comment]
@nywilken LGTM 

btw, @Direnol  also the same codeowner as me. I'll add him to the CODEOWNERS file.

**Review by nywilken — APPROVED** [review]

**Comment by nywilken** [comment]
> @nywilken LGTM
> 
> btw, @Direnol also the same codeowner as me. I'll add him to the CODEOWNERS file.

Got it, thanks for that info and the CODEOWNERS PR.

**Comment by nywilken** [comment]
Thanks for the update @karitra, apologies for the longer than normal review time. The feature has been released in v1.1.2

**Pull request merged**
